### PR TITLE
Reduce coupling with pino logger

### PR DESCRIPTION
**Pull request by olalonde**
Motivation: I was having a type error because my repo was using a more recent version of pino than the one Baileys was using. 

Solution: I put the Logger type directly in the Baileys repo so that it's more easy to use a logger different from pino (or use a version of pino that's different from the one Baileys is using).

### CODE REVIEW

**Comment by olalonde** [comment]
bump

**Comment by olalonde** [comment]
Ping.

**Comment by olalonde** [comment]
Temporary hack to use another logger than pino:

```typescript
// Make a pino compatible logger for use with baileys...
import { WhatsAppClient } from ".";
import { makeWASocket } from "@whiskeysockets/baileys";

type WALogger = NonNullable<Parameters<typeof makeWASocket>[0]["logger"]>;
type WALogFn = WALogger["info"];

export function makePinoCompatibleLogger(client: WhatsAppClient): WALogger {
  function makeLogFn(level: "debug" | "info" | "warn"): WALogFn {
    return (arg1: unknown, arg2: unknown) => {
      if (typeof arg1 === "string") {
        client.logger[level](arg1, arg2);
      } else if (typeof arg2 === "string") {
        client.logger[level](arg2, arg1);
      } else {
        client.logger[level]("[meta]", arg1);
      }
    };
  }
  // FIXME: hack until PR merged: https://github.com/WhiskeySockets/Baileys/pull/325
  return {
    level: "",
    debug: makeLogFn("debug"),
    info: makeLogFn("info"),
    warn: makeLogFn("warn"),
    silent: makeLogFn("debug"),
    fatal: makeLogFn("warn"),
    error: makeLogFn("warn"),
    trace: makeLogFn("debug"),
  } as WALogger;
}
```

**Review by jlucaso1 — APPROVED** [review]

**Comment by jpsamarino** [comment]
very good, I needed to create an adapter to solve the same problem.

**Review by yury-tomaz — APPROVED** [review]
I have reviewed the code and tested the pull request locally for 'Reduce coupling with pino logger #325'.

**Comment by PurpShell** [comment]
I don't like this idea. As a hack for your use, this is alright. You can simply downgrade pino to our level. We don't want to mess up Baileys this much. We are a socket library not a logging one. Stop trying to include everything into Baileys. 
Thanks for your thoughtfulness regardless, and we hope to see you contributing more!

**Comment by olalonde** [comment]
> We are a socket library not a logging one

@purpshell that was the point of my PR. to remove the tight coupling with pino. It's a bad practice for libraries to impose a logger or log anything at all, really.

**Comment by devlikepro** [comment]
> to remove the tight coupling with pino

looks like it's done https://github.com/WhiskeySockets/Baileys/pull/1153

**Pull request closed without merging**
