### PR TITLE
Pin message

### PR DESCRIPTION
**Pull request by azudindaem**
Adding support for pin and unpin. 

Note: currently only support for web WA, not appear in device. Please review and suggest changes for device support

```ts
const pinInChatMessage = {
        key: {
            remoteJid: "123456@s.whatsapp.net",
            fromMe: true,
            id: "MsgIDXXX"
        },
        type: 1 // 1 for pin, 2 for unpin
    }

await sock.sendMessage(jid, {
    pinMessage : {
        pinInChatMessage: pinInChatMessage,
        duration: 604800 // in ms
    }
});
```

### CODE REVIEW

**Comment by eabdalmufid** [comment]
Up

**Comment by ahmadkeren** [comment]
up

**Comment by officialdittaz** [comment]
Up

**Comment by shizothetechie** [comment]
❤️🤗 Great work

**Comment by officialdittaz** [comment]
> ❤️🤗 Great work

Work on mobile app ?

**Comment by shizothetechie** [comment]
> > ❤️🤗 Great work
> 
> Work on mobile app ?

No, Message pinned but only on web version of WhatsApp. Not visible on Mobile Application. 

This will be fixed Soon :)

**Comment by officialdittaz** [comment]
> > > ❤️🤗 Great work
> > 
> > 
> > Work on mobile app ?
> 
> No, Message pinned but only on web version of WhatsApp. Not visible on Mobile Application.
> 
> This will be fixed Soon :)

up

**Comment by Auties00** [comment]
> > > ❤️🤗 Great work
> > 
> > 
> > Work on mobile app ?
> 
> No, Message pinned but only on web version of WhatsApp. Not visible on Mobile Application.
> 
> This will be fixed Soon :)

Is this fixed?

**Comment by azudindaem** [comment]
> > > > ❤️🤗 Great work
> > > 
> > > 
> > > Work on mobile app ?
> > 
> > 
> > No, Message pinned but only on web version of WhatsApp. Not visible on Mobile Application.
> > This will be fixed Soon :)
> 
> Is this fixed?

Not working on mobile device

**Comment by PurpShell** [comment]
> > > > > ❤️🤗 Great work
> > > > 
> > > > 
> > > > Work on mobile app ?
> > > 
> > > 
> > > No, Message pinned but only on web version of WhatsApp. Not visible on Mobile Application.
> > > This will be fixed Soon :)
> > 
> > 
> > Is this fixed?
> 
> Not working on mobile device

Why? Can you get it working soon?

**Comment by gusta4321** [comment]
let templategenerate= await generateWAMessageFromContent(from, proto.Message.fromObject({pinInChatMessage: {
key: message.key,
type: 1,
senderTimestampMs: new Date().getTime() / 1000
}}), {})

let templatenew = {
messageContextInfo: { messageAddOnDurationInSecs: 604800 },
...templategenerate.message
}

await conn.relayMessage(from, templatenew, { messageId: templategenerate.key.id })

It only works on WhatsApp Web.

**Pull request closed without merging**
