### PR TITLE
chore: expose makeWASocket as named

### PR DESCRIPTION
**Pull request by ekoeryanto**

### CODE REVIEW

**Comment by w3nder** [comment]
This is a feature that can break many systems.

**Comment by edgardmessias** [comment]
@w3nder , I think no, because he kept the default export.

> This is a feature that can break many systems.

**Review by edgardmessias — APPROVED** [review]

**Comment by kbiits** [comment]
Why we need to export it as a named export ? I don't see the benefits, maybe @ekoeryanto can explain this ?

**Comment by ekoeryanto** [comment]
consistency import, sometime we need to alter the tsconfig to set allowSyntaticdefaultimport or so

**Comment by lucaspereirasouzat** [comment]
How to fix Im having this problem when run build version

image

**Pull request merged**
