### PR TITLE
Pairing code login for Web API 

### PR DESCRIPTION
**Pull request by Auties00**
https://github.com/WhiskeySockets/Baileys/issues/248
It should be working already

### CODE REVIEW

**Comment by burstfreeze** [comment]
You are an absolute wizard 🪄

**Comment by burstfreeze** [comment]
What should be the phone number format? I get the Pairing code in the Baileys logs but nothing happens on my phone.

Additionally, I have a little race condition with the log output:

```
using WA v2.2325.3, isLatest: true
Please enter your mobile phone number:
{"level":30,"time":
logs logs
logs logs
logs logs
logs logs
logs logs
logs logs
logs logs
> 
```

Of course the ping messages will eventually push things down but would it make sense to arbitrarily delay the prompt by one second so at least for a short time it will be the bottom-most line?

**Comment by Auties00** [comment]
> What should be the phone number format? I get the Pairing code in the Baileys logs but nothing happens on my phone.
> 
> Additionally, I have a little race condition with the log output:
> 
> ```
> using WA v2.2325.3, isLatest: true
> Please enter your mobile phone number:
> {"level":30,"time":
> logs logs
> logs logs
> logs logs
> logs logs
> logs logs
> logs logs
> logs logs
> > 
> ```
> 
> Of course the ping messages will eventually push things down but would it make sense to arbitrarily delay the prompt by one second so at least for a short time it will be the bottom-most line?

type the number with the country code(no spaces or parenthesis, just like a jid)
a notification should arrive on your phone about someone logging in 
type the code 
it should pair up

**Comment by burstfreeze** [comment]
My bad, it worked with the jid format :)

**Comment by burstfreeze** [comment]
Now I was caught in an infinite 

```
connection update {
  connection: 'connecting',

connection update {
  connection: 'close',
  
  connection update {
  connection: 'connecting',

connection update {
  connection: 'close',
```

loop. Will check again on another network

**Comment by Auties00** [comment]
> Now I was caught in an infinite
> 
> ```
> connection update {
>   connection: 'connecting',
> 
> connection update {
>   connection: 'close',
>   
>   connection update {
>   connection: 'connecting',
> 
> connection update {
>   connection: 'close',
> ```
> 
> loop. Will check again on another network

Yeah I noticed that too just now, yet the pairing is successful

**Comment by Auties00** [comment]
nvm, it's fixed now.
I missed a couple of events, so the identity wasn't serialized correctly

**Review by DavidsonGomes — APPROVED** [review]
Very Good!

**Comment by bentacos** [comment]
@Auties00 my man strikes again. awesome work dude!

**Review by dgcode-tec — APPROVED** [review]
Tested here, it's amazing

**Comment by burstfreeze** [comment]
Was able to log in and send a message. Incredible work

**Review by burstfreeze — APPROVED** [review]

**Review by andresayac — APPROVED** [review]

**Comment by edgardmessias** [comment]
@Auties00 , please use https://www.conventionalcommits.org/en/v1.0.0/ to allow to generete the Changelog files.

As an alternative, you can squash and edit the commit message

**Comment by alexandrereyes** [comment]
It's not working anymore: https://github.com/WhiskeySockets/Baileys/issues/328

**Comment by OlegPrg** [comment]
Here's the right solution
 browser: ['Windows','CHROME','121.0.6167.87'],

**Pull request merged**
