### PR TITLE
Implementation to allow saving authentication data in MySql + multiple sessions

### PR DESCRIPTION
**Pull request by bobpetrov**
It's simple to use

```ts
const { state, saveCreds, removeCreds } = await useMySQLAuthState({
    session: 'session-1',
    host: 'localhost',
    user: 'root',
    password: 'Password123#',
    database: 'baileys'
})
```

```sql
CREATE TABLE `auth` (
	`session` varchar(50) NOT NULL,
	`id` varchar(100) NOT NULL,
	`value` json DEFAULT NULL,
	UNIQUE KEY `idxunique` (`session`,`id`),
	KEY `idxsession` (`session`),
	KEY `idxid` (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
```

### CODE REVIEW

**Comment by MSufianS** [comment]
@FortisEtMagnus Is possible using prisma.io? because prisma.io have multi database provider.

Thank you...

**Comment by binhodev** [comment]
> In my opinion, this feature should not be the responsibility of Baileys; it should belong to whoever is consuming it. Because each application that uses Baileys can use a different database. If you don't use an ORM, you will only increase complexity; it's more code inside the lib.
> 
> 
> 
> Because they are basically duplicating the code and adapting

I agree... 
This or any database implementation don't necessary.

**Comment by pedroota** [comment]
I think we should create a package for each database to integrate baileys. For example @WhiskeySockets/Baileys/mysql or @WhiskeySockets/Baileys/mongo

**Comment by Auties00** [comment]
Sorry but the idea of Baileys is to provide a non opinionated library. You are more then welcome to publish this as a separate package as others have suggested. Anyways thanks for your contributions anyways!

**Pull request closed without merging**
