### PR TITLE
adjusted default keepAliveIntervalMs

### PR DESCRIPTION
**Pull request by sudomaaz**

### CODE REVIEW

**Comment by sudomaaz** [comment]
I used to face issue in larger group where members are more than 300 or 400. So whenever bot went offline and came back online while sending message it used to throw timeout error "Connection was lost". 

On investigation it was found that if user does not supplies any default value for keepAliveIntervalMs while calling makeSocket there existed issue in startKeepAliveRequest function in Socket.js

After providing this value in socket configurartion there was no timeout while sending message to larger audience. 

Since Baileys does not do any mandatory passing of this param in socket added a default value of 5min in milliseconds.

@adiwajshing

**Review by edgardmessias — APPROVED** [review]

**Comment by sudomaaz** [comment]
@PurpShell can you also check and approve as two required

**Review by zennn08 — COMMENTED** [review]
Maybe you can change default keepAliveIntervalMs [here](https://github.com/WhiskeySockets/Baileys/blob/e0e7d40847e8c01bbf18680bfba1682293168d5e/src/Defaults/index.ts#L57)

**Comment by sudomaaz** [comment]
@zennn08 yes made the changes in default value...to 30 milliseconds...pls check and approve

**Review by zennn08 — APPROVED** [review]

**Comment by sudomaaz** [comment]
@edgardmessias @zennn08 its still showing 2 approvals required

**Review by Fonnte — APPROVED** [review]

**Comment by sudomaaz** [comment]
@edgardmessias okay understood. Any idea when I can expect this to be merged ?

**Comment by edgardmessias** [comment]
@sudomaaz , according your report, the default value was 15 seconds, but you get disconnection. Could you check if there are the real value in the startKeepAliveRequest function?

**Comment by w3nder** [comment]
I don't believe that doubling the time from 15 to 30 will really solve the problem.

**Comment by azudindaem** [comment]
There is no need for this change. I haven't had a chance to test this PR yet, but please don't merge it until it has been properly confirmed as the solution to the problem

**Comment by azudindaem** [comment]
Sorry, i commented base on the initial PR that refer to keepAliveIntervalMs=300000 in socket.ts

By looking at the latest changed should be okay

**Comment by sudomaaz** [comment]
> @sudomaaz , according your report, the default value was 15 seconds, but you get disconnection. Could you check if there are the real value in the startKeepAliveRequest function?

@edgardmessias  no startKeepAliveRequest function works with the keepAliveIntervalMs value passed from makeSocket. I have adjusted now as 30sec in default value.

**Review by andresayac — APPROVED** [review]

**Pull request merged**
