### PR TITLE
Flush Buffer

### PR DESCRIPTION
**Pull request by makanSukros**

### CODE REVIEW

**Comment by edgardmessias** [comment]
@makanSukros , could you explain this change?

**Comment by makanSukros** [comment]
> @makanSukros , could you explain this change?

to solve the problem of messages.upsert not getting through sometimes

**Comment by kbiits** [comment]
@makanSukros no, this is not fix the root cause

I am who made this quick fix in my repo https://github.com/kbiits/Whiskey-Baileys

please don't just copy paste and made a PR for fixing, you need to do analyze the root cause

my quick fix is not solve the root cause

**Comment by Fonnte** [comment]
I personally don't experience this issue. Maybe there is something wrong with your code/ misconfigure or missing auth/ something else. I suggest to close this pr and investigate the root cause as @kbiits suggest.

**Comment by kbiits** [comment]
> I personally don't experience this issue. Maybe there is something wrong with your code/ misconfigure or missing auth/ something else. I suggest to close this pr and investigate the root cause as @kbiits suggest.

No, there's nothing wrong with my code / config, it's not just me who experienced this issue, a lot of people also experiencing this. But what i'm trying to say is My workaround is not a proper solution to solve the root cause of the issue, I never said that my workaround should merged into this official Baileys repo cause it doesn't solve the root cause, i know that.

But @makanSukros just copy my workaround and made PR to this repo, which I never do before and I also never agreed to it, I just helping people who experienced the issue to just use my repo instead of official baileys if they just want to get the things done.

I'm also downvoting this PR and suggest it to just close this

**Comment by kbiits** [comment]
> I personally don't experience this issue. Maybe there is something wrong with your code/ misconfigure or missing auth/ something else. I suggest to close this pr and investigate the root cause as @kbiits suggest.

No, I don't thinks it's not from the code / configuration. A lot of people experience this issue, and I still can't figure out what the root cause is and why the buffer is not flushed. Currently I don't have any spare time to investigate it more. But what I can say is it's not from the client code / configuration

**Comment by edgardmessias** [comment]
I agree with @kbiits , we need to investigate it.

**Comment by Guilherme-j10** [comment]
I don't know if this could be related to the timedouts that occur with me and others using the code. But after some time connected it becomes unfeasible to use the message sending and number validation methods, if your defaultQueryTimeoutMs is not set to undefined a TimedOut error message will be printed in the terminal, at least the only simple way to solve this is by stopping the application and starting again, programmatically to do this becomes somewhat complex, as in my case I had to use child_process. Anyway, I already opened an issue on the old repo to talk about the subject and almost no one responded, but talking to some developers who use Baileys, everyone goes through this problem, including investigating a little deeper into the issues related to this subject this problem is even a little old and at least no one has been able to solve this problem at the root, not even Adi himself

**Comment by tiagomatrixd** [comment]
> Não sei se isso pode estar relacionado aos tempos limite que ocorrem comigo e com outras pessoas usando o código. Mas depois de algum tempo conectado torna-se inviável usar os métodos de envio de mensagens e validação de número, se o seu defaultQueryTimeoutMs não estiver definido como undefined uma mensagem de erro TimedOut será impressa no terminal, pelo menos a única maneira simples de resolver isso é parando o aplicativo e começando novamente, programaticamente para fazer isso se torna um pouco complexo, como no meu caso eu tive que usar child_process. Enfim, já abri uma edição no antigo repo para falar sobre o assunto e quase ninguém respondeu, mas conversando com alguns desenvolvedores que usam Baileys, todo mundo passa por esse problema, inclusive investigando um pouco mais a fundo nas questões relacionadas a esse assunto esse problema é até um pouco antigo e pelo menos ninguém conseguiu resolver esse problema na raiz, nem mesmo o próprio Adi

tell me how you solved it, this problem is a headache.

**Comment by tudonetwork** [comment]
With this, started to receive the: recv messages and chats.update

**Pull request closed without merging**
