### PR TITLE
Deprecation of buttons

### PR DESCRIPTION
**Pull request by PurpShell**
[Support my work on GitHub Sponsors](https://github.com/sponsors/PurpShell)

# Deprecation of Buttons, Lists, Templates
We will now remove all references in code and built-in capability to send buttons or Lists. We announced the deprecation a year and a few months ago.

This PR allows you to add custom Nodes to the outgoing <message> as well. Do with that information what you will!

### CODE REVIEW

**Comment by PurpShell** [comment]
> Why don't just use interactionMessage for buttons

This PR is to deprecate all buttons, no more buttons, no more interaction message, no more anything!

**Comment by Xyro-Dev** [comment]
yatta🥰

**Comment by Galang-Purnama** [comment]
> > Why don't just use interactionMessage for buttons
> 
> This PR is to deprecate all buttons, no more buttons, no more interaction message, no more anything!

Why ?

**Comment by lz20r** [comment]
> Ok.. buttons are still working...

Better than nothing 😔

**Comment by lz20r** [comment]
> > Why don't just use interactionMessage for buttons
> 
> 
> 
> This PR is to deprecate all buttons, no more buttons, no more interaction message, no more anything!

That makes it more interactive.. and not static...

**Comment by Galang-Purnama** [comment]
> > > Why don't just use interactionMessage for buttons
> > 
> > 
> > This PR is to deprecate all buttons, no more buttons, no more interaction message, no more anything!
> 
> This makes it more interactive... and not static... In my opinion, buttons improve the visualization of information and also prevent the user from getting tired of seeing the same format. Another advantage is that it allows you to have a certain way of shaping it to your liking. Also, creating your own design would make the bot not look like a copy of others.

I agree with what you said, but the Baileys developers don't want us to have a simple bot, they only make it more difficult if the button is no longer there.

**Comment by APdev93** [comment]
Is the number of sending button messages reduced to a maximum of 3?, to reduce the risk of bugs and etc?

**Comment by RynXD-Host** [comment]
I've had enough with buttons😌

**Comment by PurpShell** [comment]
We already took our decision and informed and warned everyone a year ago. No more buttons.

Meta directly patched my own work (50 hours spent uncovering <biz>) 1 day after I made a push to pedroslopez/whatsapp-web.js

We don't want provocation or reasons for baileys to be targeted. It is either buttons or baileys, pick one.

GO USE THE OFFICIAL META API IF YOU CARE ABOUT UI/UX I PERSONALLY COULD CARE LESS!

**Comment by adithyan-hermit** [comment]
> We already took our decision and informed and warned everyone a year ago. No more buttons.
> 
> Meta directly patched my own work (50 hours spent uncovering ) 1 day after I made a push to pedroslopez/whatsapp-web.js
> 
> We don't want provocation or reasons for baileys to be targeted. It is either buttons or baileys, pick one.
> 
> GO USE THE OFFICIAL META API IF YOU CARE ABOUT UI/UX I PERSONALLY COULD CARE LESS!

Screenshot_2024-07-31-22-56-17-14_6012fa4d4ddec268fc5c7112cbb265e7
Can you let me know is there any reasons that pulling baileys dev to not implement interactionMessage for buttons?

**Comment by PurpShell** [comment]
I already mentioned the reason, Meta doesn't like it.

We have received multiple legal threats.

**Pull request merged**
