### PR TITLE
feat: auto version hash

### PR DESCRIPTION
**Pull request by ugurgungezerler**

### CODE REVIEW

**Review by azudindaem — APPROVED** [review]

**Comment by Auties00** [comment]
I also implemented this in my library.
The only issue is that we don't have any API to fetch and use the latest Whatsapp version for the hashing method.
Maybe we should host the latest version at https://github.com/WhiskeySockets/Baileys/blob/master/src/Defaults/baileys-version.json, just like we do for the web, so no lib upgrades are required

**Comment by PurpShell** [comment]
> I also implemented this in my library. The only issue is that we don't have any API to fetch and use the latest Whatsapp version for the hashing method. Maybe we should host the latest version at https://github.com/WhiskeySockets/Baileys/blob/master/src/Defaults/baileys-version.json, just like we do for the web, so no lib upgrades are required

sounds good but for now just having a proper token generation is enough

**Review by PurpShell — APPROVED** [review]
looks good to me, thanks for your first contribution!

**Review by PurpShell — CHANGES_REQUESTED** [review]
sort the imports. Just put the crypto import in the first line

**Review by canove — APPROVED** [review]

**Pull request merged**
