### PR TITLE
add option to send message to specific jid

### PR DESCRIPTION
**Pull request by vinikjkkj**
this option already exists in relayMessage, but i put it in sendMessage MiscMessageGenerationOptions for usability

### CODE REVIEW

**Comment by Riders004** [comment]
Example ?

**Comment by vinikjkkj** [comment]
in group:

conn.sendMessage(jid, {text: 'hello'}, {participant: {jid: user})

**Comment by Riders004** [comment]
> in group:
> 
> sock.sendMessage(jid, {text: 'hello'}, {participant: {jid: user})

What is jid user ?

**Review by Riders004 — APPROVED** [review]

**Review by Riders004 — APPROVED** [review]

**Comment by vinikjkkj** [comment]
> > in group:
> > sock.sendMessage(jid, {text: 'hello'}, {participant: {jid: user})
> 
> What is jid user ?

any participant of group .....@s.whatsapp.net

**Comment by PurpShell** [comment]
This is not a proper application of sendMessage. This participant option is used to send to ONLY ONE DEVICE in a group/chat. This is only used for sync, and other internal processes that use relayMessage. You shouldn't have this in sendMessage

**Pull request closed without merging**
