### PR TITLE
Fix error storage

### PR DESCRIPTION
**Pull request by robsonwr**
Fix error storage

### CODE REVIEW

**Review by GabrielBursi — APPROVED** [review]

**Review by ropehapi — APPROVED** [review]
Everything ok. I ran in my environment and worked perfectly

**Review by ropehapi — APPROVED** [review]

**Comment by sabrowi** [comment]
Why these PR not merged yet, i need it, please merge.

**Comment by azudindaem** [comment]
Why? This is not necessary. nothing to do with fix error storage

**Comment by sabrowi** [comment]
> Why? This is not necessary. nothing to do with fix error storage

I encountered an error about it.

node_modules/@whiskeysockets/baileys/lib/Store/make-cache-manager-store.d.ts:2:50 - error TS2552: Cannot find name 'Store'. Did you mean 'Storage'?

2 declare const makeCacheManagerAuthState: (store: Store, sessionKey: string) => Promise<{
                                                   ~~~~~

  node_modules/typescript/lib/lib.dom.d.ts:13994:13
    13994 declare var Storage: {
                      ~~~~~~~
    'Storage' is declared here.

[4:18:25 PM] Found 1 error. Watching for file changes.

#633

**Comment by PurpShell** [comment]
Not possible to merge. Sorry but I'll be force closing this and merging my own PR (with credit to you), in order to save time.

**Pull request closed without merging**
