### PR TITLE
Label support

### PR DESCRIPTION
**Pull request by rawars**
Support for labels is added, a PR that @kuzalekon made was used, it was awaiting review in the previous repository before being removed, an update was also added in the README.md where it is explained how to apply the events for the labels as well as the example.ts script was updated.

### CODE REVIEW

**Review by edgardmessias — APPROVED** [review]

**Comment by rawars** [comment]
@edgardmessias It's already finished, the only thing left is for them to approve it, it's my first PR and I'm not sure what the process is, it says that two users have to approve.

**Comment by edgardmessias** [comment]
@rawars why you removed my review?

**Comment by rawars** [comment]
> @rawars why you removed my review?

Friend, it is that by mistake I clicked on a button, which had some arrows, sorry, it seemed strange to me that your review no longer appeared.

**Comment by rawars** [comment]
> @rawars why you removed my review?

It is that it is my first PR, I do not understand the flow well.

**Review by edgardmessias — APPROVED** [review]

**Comment by rawars** [comment]
@edgardmessias Can you apply it again?

**Comment by Manjit2003** [comment]
Seems good 💯 
+1

**Comment by Cloudcitycolombia** [comment]
+1

**Review by azudindaem — APPROVED** [review]
good to go.. we can improve later.. the most importtant thing its works for both chat and message label..

the only thing we need to sort out is on history part

**Comment by rawars** [comment]
> good to go.. we can improve later.. the most importtant thing its works for both chat and message label..
> 
> the only thing we need to sort out is on history part

Greetings friend, thanks for taking the time to check the PR, could you be a little more specific about the story?

**Comment by azudindaem** [comment]
Why did you close the PR? Overall, this PR is okay. The next step to be done is to ensure that the labels in HistorySync are functioning properly.

**Review by PurpShell — APPROVED** [review]
Looks nice, as long as the formatting changes don't kill ESLint, we are fine. Merging

**Comment by FlavioCoutinhoGO** [comment]
Hi @rawars are you ok? Were you able to use the tags in your code? On discord no one answers me... I talked to a Brazilian who wanted to charge me 1 thousand dollars to help me. I actually read all the documentation and I don't know how to get what I want. I need help please.

**Comment by rawars** [comment]
Hello, by what means can I contact you?

**Comment by FlavioCoutinhoGO** [comment]
> Hello @FlavioCoutinhoGO , by what means can I contact you?

WhatsApp: +5562982673456

**Pull request merged**
