### PR TITLE
feat: Send Status (status@broadcast) {text, media, audio(with waveform)}

### PR DESCRIPTION
**Pull request by DavidsonGomes**
Requesting this PR again, with corrections

This PR makes it possible to send all types of status (text, image, video, audio with waveforms) in addition to also allowing the sending of audios with waveform to contacts and groups.

/***** How to send text status by setting font style and background color */

sock.sendMessage('status@broadcast', {
text: 'Hi my friends!' //is link preview compatible
}, {
backgroundColor: '#315575',
font: 3,
//it is always necessary to inform the list of contacts that will have access to the posted status
statusJidList: ['[55xxxxxxxxxxx@s.whatsapp.net](mailto:55xxxxxxxxxxx@s.whatsapp.net)', '[55xxxxxxxxxxx@s.whatsapp.net](mailto:55xxxxxxxxxxx@s.whatsapp.net)']
});

/***** How to send audio status with waveforms and background color */

var audio = fs.readFileSync('./audio.mp3');
sock.sendMessage('status@broadcast',
{
audio: audio,
mimetype: 'audio/mp4',
ptt: 'true'
}, {
backgroundColor: '#315575',
//it is always necessary to inform the list of contacts that will have access to the posted status
statusJidList: ['[55xxxxxxxxxxx@s.whatsapp.net](mailto:55xxxxxxxxxxx@s.whatsapp.net)', '[55xxxxxxxxxxx@s.whatsapp.net](mailto:55xxxxxxxxxxx@s.whatsapp.net)']
})

Credits: https://github.com/vphelipe

### CODE REVIEW

**Comment by DIO85-git** [comment]
Thanks! Please approve this!

**Comment by daniloruizdasilva** [comment]
Very good!

**Comment by HermesMacedo** [comment]
Thanks, approve this!

**Review by azudindaem — APPROVED** [review]
Latest PR is good to go

**Review by stactus — APPROVED** [review]
I did several tests here sending texts, images, short videos and audios and it worked perfectly.

An excellent resource that will help many users.

Congratulations to [Víctor Phelipe](https://github.com/vphelipe) for creating and @DavidsonGomes for reinforcing it.

**Review by eabdalmufid — APPROVED** [review]

**Comment by unilogica** [comment]
Thanks! Nice feature.

**Comment by vaccarieli** [comment]
I have more than 2000 contacts. So, when I try to send the list with all of them, it hangs. Any suggestions? @DavidsonGomes

**Comment by DavidsonGomes** [comment]
> I have more than 2000 contacts. So, when I try to send the list with all of them, it hangs. Any suggestions? @DavidsonGomes

One solution is to divide this list and send it by parts

**Comment by vaccarieli** [comment]
> 

I divided into 4 different parts 500 each. However, the same image is posted 4 times. Is there a way to send those lists to the same image id?

**Comment by A-d-i-t-h-y-a-n** [comment]
How to delete status 👀

**Comment by calix666** [comment]
days before its work perfect but now : Time out

**Comment by sg957** [comment]
Hey
I use this update to send statuses
And I encounter 2 problems

One problem when sending a status to a large amount of people is getting an error
```
"stack": "Error: Connection Closed\n at sendRawMessage (/app/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:54:19)\n at sendNode (/app/node_modules/@adiwajshing/baileys /lib/Socket/socket.js:73:16)\n at query (/app/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:137:15)\n at getUSyncDevices (/app/node_modules/ @adiwajshing/baileys/lib/Socket/messages-send.js:166:30)\n at /app/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:305:53\n at process. processTicksAndRejections (node:internal/process/task_queues:95:5)\n at async Object.transaction (/app/node_modules/@adiwajshing/baileys/lib/Utils/auth-utils.js:136:26)\n at async relayMessage (/app/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:278:9)\n at async Object.sendMessage (/app/node_modules/@adiwajshing/baileys/lib/Socket/messages- send.js:648:17)\n at async /app/node_modules/@nestjs/core/router/router-execution-context.js:46:28\n at async /app/node_modules/@nestjs/core/router /router-proxy.js:9:17",
         "message": "Connection Closed",

```
Another problem I am having
When sending a video or photo through this, the status does not have a preview background image
That is, until the video has finished downloading, the viewer sees a black or gray screen, unlike the normal status sent through the phone, where you can see a preview of the video in a blurry display

I would appreciate it if someone could help with this

**Comment by Aal-oss** [comment]
> Requesting this PR again, with corrections
> 
> This PR makes it possible to send all types of status (text, image, video, audio with waveforms) in addition to also allowing the sending of audios with waveform to contacts and groups.
> 
> /***** How to send text status by setting font style and background color */
> 
> sock.sendMessage('status@broadcast', { text: 'Hi my friends!' //is link preview compatible }, { backgroundColor: '#315575', font: 3, //it is always necessary to inform the list of contacts that will have access to the posted status statusJidList: ['[55xxxxxxxxxxx@s.whatsapp.net](mailto:55xxxxxxxxxxx@s.whatsapp.net)', '[55xxxxxxxxxxx@s.whatsapp.net](mailto:55xxxxxxxxxxx@s.whatsapp.net)'] });
> 
> /***** How to send audio status with waveforms and background color */
> 
> var audio = fs.readFileSync('./audio.mp3'); sock.sendMessage('status@broadcast', { audio: audio, mimetype: 'audio/mp4', ptt: 'true' }, { backgroundColor: '#315575', //it is always necessary to inform the list of contacts that will have access to the posted status statusJidList: ['[55xxxxxxxxxxx@s.whatsapp.net](mailto:55xxxxxxxxxxx@s.whatsapp.net)', '[55xxxxxxxxxxx@s.whatsapp.net](mailto:55xxxxxxxxxxx@s.whatsapp.net)'] })
> 
> Credits: https://github.com/vphelipe

How to cover everyone?

**Comment by Fann-level-MAX** [comment]
can i send text broadcast with custom text color?
or custom color is only available for background?
thank you.

**Comment by Fann-level-MAX** [comment]
> > Requesting this PR again, with corrections
> > This PR makes it possible to send all types of status (text, image, video, audio with waveforms) in addition to also allowing the sending of audios with waveform to contacts and groups.
> > /***** How to send text status by setting font style and background color */
> > sock.sendMessage('status@broadcast', { text: 'Hi my friends!' //is link preview compatible }, { backgroundColor: '#315575', font: 3, //it is always necessary to inform the list of contacts that will have access to the posted status statusJidList: ['[55xxxxxxxxxxx@s.whatsapp.net](mailto:55xxxxxxxxxxx@s.whatsapp.net)', '[55xxxxxxxxxxx@s.whatsapp.net](mailto:55xxxxxxxxxxx@s.whatsapp.net)'] });
> > /***** How to send audio status with waveforms and background color */
> > var audio = fs.readFileSync('./audio.mp3'); sock.sendMessage('status@broadcast', { audio: audio, mimetype: 'audio/mp4', ptt: 'true' }, { backgroundColor: '#315575', //it is always necessary to inform the list of contacts that will have access to the posted status statusJidList: ['[55xxxxxxxxxxx@s.whatsapp.net](mailto:55xxxxxxxxxxx@s.whatsapp.net)', '[55xxxxxxxxxxx@s.whatsapp.net](mailto:55xxxxxxxxxxx@s.whatsapp.net)'] })
> > Credits: https://github.com/vphelipe
> 
> How to cover everyone?

/* Get all contact from store */
var contacts = Object.keys(store.contacts);

/* Filter to remove any invalid contacts */
contacts = contacts.filter(contact => contact.includes('@s.whatsapp.net'));

/* Send broadcast with filtered contacts */
sock.sendMessage('status@broadcast', 
            { text: "test" }, {
                backgroundColor: '#212121',
                font: 3,
                statusJidList: contacts
            }
}

**Comment by AKAZAMD** [comment]
thanks bro

Pada Sabtu, 22 Juni 2024, irfan ***@***.***> menulis:

**Comment by AKAZAMD** [comment]
but how do I get to the store

Pada Sabtu, 22 Juni 2024, irfan ***@***.***> menulis:

**Comment by Fann-level-MAX** [comment]
> > Requesting this PR again, with corrections
> > This PR makes it possible to send all types of status (text, image, video, audio with waveforms) in addition to also allowing the sending of audios with waveform to contacts and groups.
> > /***** How to send text status by setting font style and background color */
> > sock.sendMessage('status@broadcast', { text: 'Hi my friends!' //is link preview compatible }, { backgroundColor: '#315575', font: 3, //it is always necessary to inform the list of contacts that will have access to the posted status statusJidList: ['[55xxxxxxxxxxx@s.whatsapp.net](mailto:55xxxxxxxxxxx@s.whatsapp.net)', '[55xxxxxxxxxxx@s.whatsapp.net](mailto:55xxxxxxxxxxx@s.whatsapp.net)'] });
> > /***** How to send audio status with waveforms and background color */
> > var audio = fs.readFileSync('./audio.mp3'); sock.sendMessage('status@broadcast', { audio: audio, mimetype: 'audio/mp4', ptt: 'true' }, { backgroundColor: '#315575', //it is always necessary to inform the list of contacts that will have access to the posted status statusJidList: ['[55xxxxxxxxxxx@s.whatsapp.net](mailto:55xxxxxxxxxxx@s.whatsapp.net)', '[55xxxxxxxxxxx@s.whatsapp.net](mailto:55xxxxxxxxxxx@s.whatsapp.net)'] })
> > Credits: https://github.com/vphelipe
> 
> How to cover everyone?

to get to the store it's quite easy:

const { makeInMemoryStore } = require("@whiskeysockets/baileys")

const store = makeInMemoryStore({
    logger: pino().child({
        level: 'silent',
        stream: 'store'
    })
})
try { store.readFromFile('./store.json') } catch(e) {}
setInterval(() => {
	store.writeToFile('./store.json')
	const tempStore = JSON.parse(fs.readFileSync('./store.json', 'utf-8'));
	delete tempStore.messages;
	fs.writeFileSync('./store.json', JSON.stringify(tempStore, null, 2));
}, 10000) // save store every 10 sec

/*
-------- connect to bailey --------
const sock = makeWASocket()
and then bind store to sock
*/

store.bind(sock.ev)

// access store by doin store.blablavla

**Comment by Riders004** [comment]
> > > Requesting this PR again, with corrections
> > > This PR makes it possible to send all types of status (text, image, video, audio with waveforms) in addition to also allowing the sending of audios with waveform to contacts and groups.
> > > /***** How to send text status by setting font style and background color _/
> > > sock.sendMessage('status@broadcast', { text: 'Hi my friends!' //is link preview compatible }, { backgroundColor: '#315575', font: 3, //it is always necessary to inform the list of contacts that will have access to the posted status statusJidList: ['[55xxxxxxxxxxx@s.whatsapp.net](mailto:55xxxxxxxxxxx@s.whatsapp.net)', '[55xxxxxxxxxxx@s.whatsapp.net](mailto:55xxxxxxxxxxx@s.whatsapp.net)'] });
> > > /_**** How to send audio status with waveforms and background color */
> > > var audio = fs.readFileSync('./audio.mp3'); sock.sendMessage('status@broadcast', { audio: audio, mimetype: 'audio/mp4', ptt: 'true' }, { backgroundColor: '#315575', //it is always necessary to inform the list of contacts that will have access to the posted status statusJidList: ['[55xxxxxxxxxxx@s.whatsapp.net](mailto:55xxxxxxxxxxx@s.whatsapp.net)', '[55xxxxxxxxxxx@s.whatsapp.net](mailto:55xxxxxxxxxxx@s.whatsapp.net)'] })
> > > Credits: https://github.com/vphelipe
> > 
> > 
> > How to cover everyone?
> 
> /* Get all contact from store */ var contacts = Object.keys(store.contacts);
> 
> /* Filter to remove any invalid contacts */ contacts = contacts.filter(contact => contact.includes('@s.whatsapp.net'));
> 
> /* Send broadcast with filtered contacts */ sock.sendMessage('status@broadcast', { text: "test" }, { backgroundColor: '#212121', font: 3, statusJidList: contacts } }

Not working

**Comment by Riders004** [comment]
> > Requesting this PR again, with corrections
> > This PR makes it possible to send all types of status (text, image, video, audio with waveforms) in addition to also allowing the sending of audios with waveform to contacts and groups.
> > /***** How to send text status by setting font style and background color */
> > sock.sendMessage('status@broadcast', { text: 'Hi my friends!' //is link preview compatible }, { backgroundColor: '#315575', font: 3, //it is always necessary to inform the list of contacts that will have access to the posted status statusJidList: ['[55xxxxxxxxxxx@s.whatsapp.net](mailto:55xxxxxxxxxxx@s.whatsapp.net)', '[55xxxxxxxxxxx@s.whatsapp.net](mailto:55xxxxxxxxxxx@s.whatsapp.net)'] });
> > /***** How to send audio status with waveforms and background color */
> > var audio = fs.readFileSync('./audio.mp3'); sock.sendMessage('status@broadcast', { audio: audio, mimetype: 'audio/mp4', ptt: 'true' }, { backgroundColor: '#315575', //it is always necessary to inform the list of contacts that will have access to the posted status statusJidList: ['[55xxxxxxxxxxx@s.whatsapp.net](mailto:55xxxxxxxxxxx@s.whatsapp.net)', '[55xxxxxxxxxxx@s.whatsapp.net](mailto:55xxxxxxxxxxx@s.whatsapp.net)'] })
> > Credits: https://github.com/vphelipe
> 
> How to cover everyone?

Not working

**Pull request merged**
