### PR TITLE
adding @adiwajshing/keyed-db to dependencies

### PR DESCRIPTION
**Pull request by OSintt**
throws error 

node_modules/.pnpm/@whiskeysockets+baileys@6.2.1_a9c255cd4f7c72f8caee0a723a9801d6/node_modules/@whiskeysockets/baileys/lib/Store/make-in-memory-store.d.ts:1:21 - error TS2307: Cannot find module '@adiwajshing/keyed-db' or its corresponding type declarations.

1 import KeyedDB from '@adiwajshing/keyed-db';

if it's not installed

### CODE REVIEW

**Comment by dudagervasio** [comment]
This will help a lot of people asking  in discord how to solve it... but it is a dependency just for who uses inMemoryStore.

Everyone can solve it quickly... but so much people that do not even know js/ts wants to use Baileys....

Maybe upgrading the docs helps too.

If aproved, maybe you can remove it from devDependencies

**Comment by zennn08** [comment]
This pull request is unnecessary, because basically not everyone uses the store and needs `@adiwajshing/keyed-db`.  And for the error you mentioned, it has been fixed in commit 6ed9298d960c2a14eeaa7b42206119a6693857fd

**Comment by dudagervasio** [comment]
@zennn08 with all respect, but your PR does not fix "**Cannot find module '@adiwajshing/keyed-db'**". Only thing that fix it, is installing the package. I agree with @edgardmessias. And it will save a lot of reading time in discord about this problem. But the right is "Migrating @adiwajshing/keyed-db to dependencies"...

**Comment by zennn08** [comment]
it's ok, I'm just expressing my opinion, the decision rests with the repository owner

**Pull request merged**
