### PR TITLE
Update baileys-version.json

### PR DESCRIPTION
**Pull request by w3nder**

### CODE REVIEW

**Comment by DavidsonGomes** [comment]
Up

**Review by jrrcdev — APPROVED** [review]

**Review by arthursimas1 — APPROVED** [review]
it fixed the latest connection problem here

**Comment by T3uZ** [comment]
up

**Comment by jonhy751** [comment]
up

**Comment by gusta4321** [comment]
UP

**Review by gusta4321 — APPROVED** [review]
OK

**Comment by barkerpedro** [comment]
up

**Review by Fonnte — APPROVED** [review]

**Review by tiagomatrixd — APPROVED** [review]
worked

**Review by renatoiub — APPROVED** [review]

**Comment by KazeDevID** [comment]
kiss me

**Comment by acorreane** [comment]
worked ❤️

**Comment by IstiantoIlham** [comment]
Nice😊

**Comment by kj2222** [comment]
Does this resolve the Indian numbers logging out issue? Doesn't seem to be

**Comment by dephea** [comment]
@kj2222 I believe it is not related

**Comment by bhavesh53** [comment]
> Does this resolve the Indian numbers logging out issue? Doesn't seem to be

no

**Comment by devsofolink** [comment]
up

**Comment by AKAZAMD** [comment]
npm ERR! error: pathspec 'patch-1;' did not match any file(s) known to git

**Pull request merged**
