### PR TITLE
style: fixed and relaxed style lint

### PR DESCRIPTION
**Pull request by edgardmessias**

### CODE REVIEW

**Comment by burstfreeze** [comment]
About the linting - what are the implications here? Didn't the commits on the original repo all pass the lint for the same code?

**Comment by edgardmessias** [comment]
I don't know why, probably the original repository was using a old commit or something like this, the fact is: there are somethings to fix

**Comment by edgardmessias** [comment]
My main idea is: fix the main workflow and fix all any types later, because we need investigation on each case

**Review by burstfreeze — APPROVED** [review]
I am still not entirely sold on the idea but as the lint does not affect the project at runtime I am on your side here.

**Review by Auties00 — APPROVED** [review]

**Pull request merged**
