### PR TITLE
Feat: add authors who perform participant updates

### PR DESCRIPTION
**Pull request by aliazhar-id**

### CODE REVIEW

**Comment by DavidModzz** [comment]
I tested it and it works correctly

**Review by Ismananda — APPROVED** [review]
I tested it and it works correctly, so cool

**Review by azudindaem — APPROVED** [review]

**Review by Auties00 — APPROVED** [review]

**Comment by programadorbob** [comment]
Works correctly

**Review by zennn08 — APPROVED** [review]

**Review by edgardmessias — APPROVED** [review]

**Review by PurpShell — APPROVED** [review]
lgtm

**Pull request merged**
