### PR TITLE
fix: get poll request from getAggregateVotesInPollMessage in v1 v2 v3

### PR DESCRIPTION
**Pull request by andresayac**
image
image

### CODE REVIEW

**Review by edgardmessias — APPROVED** [review]

**Comment by Auties00** [comment]
why would they have 3 versions is my question though?

**Comment by edgardmessias** [comment]
They are evolving how polls work.

The v3 is related to acception only one selection

**Comment by andresayac** [comment]
> why would they have 3 versions is my question though?

https://github.com/WhiskeySockets/Baileys/blob/9434e12730b9e8c1f0a2314c5a3f67d391feb7f4/WAProto/WAProto.proto#L706
image

**Comment by Auties00** [comment]
> They are evolving how polls work.
> 
> The v3 is related to acception only one selection

i mean i don't see why they aren't using the metadata object that's in every poll message, but i guess I'm not a WhatsApp engineer

**Review by Auties00 — APPROVED** [review]

**Pull request merged**
