### PR TITLE
added latest pending baileys commit

### PR DESCRIPTION
**Pull request by andresayac**
refactor: store w transaction:  https://github.com/andresayac/Baileys/commit/a8e26c6eb378c8a65def57b010a1bb31d0bc40fa
fix: auth store transactions + tests: https://github.com/andresayac/Baileys/commit/1802da12a4cd929a9f1d23668792011edbcf0a38

### CODE REVIEW

**Comment by burstfreeze** [comment]
I compared the repo with the "last known original" at https://github.com/w3nder/baileys/commit/1802da12a4cd929a9f1d23668792011edbcf0a38

The only differences I can see are changes in messages-send.ts are what auties added in 28be45a

In other words, not a single line of code that was not present in Adi's repo so it's clean and good to merge from my end.

**Comment by Fonnte** [comment]
> I compared the repo with the "last known original" at [w3nder/baileys@1802da1](https://github.com/w3nder/baileys/commit/1802da12a4cd929a9f1d23668792011edbcf0a38)
> 
> The only differences I can see are changes in messages-send.ts are what auties added in [28be45a](https://github.com/WhiskeySockets/Baileys/commit/28be45a9b44b3480140a3890e2397cb211b435b2)
> 
> In other words, not a single line of code that was not present in Adi's repo so it's clean and good to merge from my end. The only improvement would be to rather use the original commit hashes and author but since it contributes to less than 0.01% of the commits from adi I think that's okay

without this PR, the sessionError as #14 will happen much more frequent and on some devices, can't even do anything. on these devices, send message or receiving upsert message is not possible. on success devices, when the volume is high, the no session error will prevent the message from being sent.  these last 2 commit solves the problem most of the time .

**Comment by andresayac** [comment]
I was doing several tests indeed I see what I comment @Fonnte  add more information for your interest
```
messages.upsert [
  {
    key: {
      remoteJid: '5732461xxxxx@s.whatsapp.net',
      fromMe: false,
      id: 'AD76837427B5A2083D6722DC0F90E549',
      participant: undefined
    },    messageTimestamp: 1682135564,
    pushName: 'BotXi',
    broadcast: false,
    message: Message {
      conversation: 'Juj',
      messageContextInfo: [MessageContextInfo]
    }
  }
] notify
{"level":20,"time":1682135564666,"pid":17276,"hostname":"LAPTOP-SV50PQ66","jidsRequiringFetch":["5732461xxxxx:3@s.whatsapp.net","5732461xxxxx:5@s.whatsapp.net","5732461xxxxx:6@s.whatsapp.net","5732461xxxxx:97@s.whatsapp.net","5730027xxxxx:45@s.whatsapp.net","5730027xxxxx:47@s.whatsapp.net","5730027xxxxx:48@s.whatsapp.net"],"msg":"fetching sessions"}
C:\laragon\www\base-baileys-memory\node_modules\libsignal\src\session_cipher.js:71
                throw new errors.SessionError("No sessions");
                      ^

SessionError: No sessions
    at 5730027xxxxx:45.0 [as awaitable] (C:\laragon\www\base-baileys-memory\node_modules\libsignal\src\session_cipher.js:71:23)
    at async _asyncQueueExecutor (C:\laragon\www\base-baileys-memory\node_modules\libsignal\src\queue_job.js:20:29)

Node.js v18.16.0
```
https://github.com/WhiskeySockets/Baileys/blob/e3f830f283f38069a1f87f4afbf451af4a261606/src/Socket/messages-send.ts#L235

**Review by burstfreeze — APPROVED** [review]
Thank you guys for reporting that the PR reduces the errors for you. As soon as #13 is merged, we will trigger the workflow again (very confident it will pass) and then merge this here too.

It seems like the workflow takes the state of the source branch (which kind of makes sense) so ignore the workflow statement, it's okay from my side.

**Review by iosahil — APPROVED** [review]

**Comment by andresayac** [comment]
Okay, if modifications are required, I'll be here.

**Review by Auties00 — APPROVED** [review]

**Comment by Auties00** [comment]
@burstfreeze sny changes you suggest? it lgtm

**Pull request merged**
