### PR TITLE
feat: Send Status (status@broadcast) {text, media, audio(with waveform)}

### PR DESCRIPTION
**Pull request by vphelipe**
This PR makes it possible to send all types of status (text, image, video, audio with waveforms) in addition to also allowing the sending of audios with waveform to contacts and groups.

/***** How to send text status by setting font style and background color */

sock.sendMessage('status@broadcast', {
    text: 'Hi my friends!' //is link preview compatible
}, {
    backgroundColor: '#315575',
    font: 3,
    //it is always necessary to inform the list of contacts that will have access to the posted status
    statusJidList: ['55xxxxxxxxxxx@s.whatsapp.net', '55xxxxxxxxxxx@s.whatsapp.net']
});

/***** How to send audio status with waveforms and background color */

var audio = fs.readFileSync('./audio.mp3');
sock.sendMessage('status@broadcast',
    {
        audio: audio,
        mimetype: 'audio/mp4',
        ptt: 'true'
    }, {
    backgroundColor: '#315575',
    //it is always necessary to inform the list of contacts that will have access to the posted status
    statusJidList: ['55xxxxxxxxxxx@s.whatsapp.net', '55xxxxxxxxxxx@s.whatsapp.net']
})

### CODE REVIEW

**Comment by DeveloperNewton** [comment]
I tested it and it worked perfectly, however, I performed other tests such as with a large list, sometimes when sending to 3000 jids or more, the error "Preconnection Closed" (or something like that) is returned. One thing I noticed, when sending a little bigger text, you need a list smaller than 3000 jids, it's possible to send for more than that just with small texts.

Summary: Working perfectly as expected!

**Review by DavidsonGomes — CHANGES_REQUESTED** [review]
I tested it here by sending all types of status, text, image with caption, video with caption and audio, it's working very well, however the last commits made today are generating an error in the installation.

More specifically:
file src/Utils/messages.ts:158:62
error TS2367: This condition will always return 'false' since the types 'boolean | undefined' and 'string' have no overlap.

In this snippet here: uploadData.ptt === 'true'

**Comment by calix666** [comment]
i tested and for me dont work.

Error: Timed Out
    at C:\Users\PC\Documents\GitHub_mis\Skybot\node_modules\@whiskeysockets\baileys\lib\Utils\generics.js:159:32 {
  data: {
    stack: 'Error\n' +
      '    at promiseTimeout (C:\\Users\\PC\\Documents\\GitHub_mis\\Skybot\\node_modules\\@whiskeysockets\\baileys\\lib\\Utils\\generics.js:154:19)\n' +
      '    at waitForMessage (C:\\Users\\PC\\Documents\\GitHub_mis\\Skybot\\node_modules\\@whiskeysockets\\baileys\\lib\\Socket\\socket.js:117:61)\n' +
      '    at query (C:\\Users\\PC\\Documents\\GitHub_mis\\Skybot\\node_modules\\@whiskeysockets\\baileys\\lib\\Socket\\socket.js:140:22)\n' +
      '    at assertSessions (C:\\Users\\PC\\Documents\\GitHub_mis\\Skybot\\node_modules\\@whiskeysockets\\baileys\\lib\\Socket\\messages-send.js:199:34)\n' +
      '    at async C:\\Users\\PC\\Documents\\GitHub_mis\\Skybot\\node_modules\\@whiskeysockets\\baileys\\lib\\Socket\\messages-send.js:364:17\n' +
      '    at async Object.transaction (C:\\Users\\PC\\Documents\\GitHub_mis\\Skybot\\node_modules\\@whiskeysockets\\baileys\\lib\\Utils\\auth-utils.js:136:26)\n' +
      '    at async relayMessage (C:\\Users\\PC\\Documents\\GitHub_mis\\Skybot\\node_modules\\@whiskeysockets\\baileys\\lib\\Socket\\messages-send.js:276:9)\n' +
      '    at async Object.sendMessage (C:\\Users\\PC\\Documents\\GitHub_mis\\Skybot\\node_modules\\@whiskeysockets\\baileys\\lib\\Socket\\messages-send.js:637:17)'
  },
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 408,
    payload: {
      statusCode: 408,
      error: 'Request Time-out',
      message: 'Timed Out'
    },
    headers: {}
  }
}

Node.js v18.12.1

**Review by DavidsonGomes — APPROVED** [review]
All right here, tested and working perfectly

**Comment by calix666** [comment]
Hola. hi how can i add this change to my proyect. the name of archives not match. i have 
messages-send.d.ts 
Message.d.ts
####.d.ts please helpme

**Review by dgcode-tec — APPROVED** [review]
All tested here and working perfectly, sending text, image, video and audio status!

**Comment by calix666** [comment]
Si funciona!!! Solo me salio una observacion con los audios. ellos se envian pero en mi perfil no lo refleja aunque este añadido en statusJidList

**Comment by edgardmessias** [comment]
@vphelipe , could you rebase this PR?

**Pull request closed without merging**
