### PR TITLE
fix: profilePictureUrl

### LINKED ISSUE #900: [BUG] reason: Error: bad-request client.profilePictureUrl()
Unhandled Rejection at: Promise {
  <rejected> Error: bad-request
      at assertNodeErrorFree (/home/user/rail-way-bot/node_modules/@whiskeysockets/baileys/lib/WABinary/generic-utils.js:56:15)
      at query (/home/user/rail-way-bot/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:140:48)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Object.profilePictureUrl (/home/user/rail-way-bot/node_modules/@whiskeysockets/baileys/lib/Socket/chats.js:442:24)
      at async EventEmitter.<anonymous> (/home/user/rail-way-bot/index.js:426:22) {
    data: 400,
    isBoom: true,
    isServer: true,
    output: { statusCode: 500, payload: [Object], headers: {} }
  }
}

### PR DESCRIPTION
**Pull request by zennn08**
fix #900

### CODE REVIEW

**Comment by rayss868** [comment]
Work

**Review by rayss868 — APPROVED** [review]

**Comment by MrHoss** [comment]
Worked fine!!

**Review by MrHoss — APPROVED** [review]
Worked fine

**Review by santosgalahack — APPROVED** [review]
Perfect!

**Comment by DavidsonGomes** [comment]
Up

**Comment by lugialo** [comment]
up

**Review by brunocgc — APPROVED** [review]
Worked fine

**Review by 4relial — APPROVED** [review]

**Comment by jadersistemas** [comment]
imagem_2024-07-03_153959745
fail

**Review by skyspablo — APPROVED** [review]

**Comment by skyspablo** [comment]
The changes are working

**Comment by odeliojr** [comment]
:thumbsup:

**Review by DavidsonGomes — APPROVED** [review]

**Comment by ainitech** [comment]
Working

**Comment by IanosJunior** [comment]
Working

**Comment by jadersistemas** [comment]
image

em localhost ok na VPS nada!

**Comment by jreboredo** [comment]
Working

**Comment by bergpinheiro** [comment]
Up

**Review by tpchagas — APPROVED** [review]
ok approve funcional

**Comment by Its-me-nishmal** [comment]
nice , working well

**Review by CSFelix — APPROVED** [review]
LGTM!!

**Comment by hudsonebert** [comment]
Funcionou.

**Review by CSFelix — APPROVED** [review]
Working on Windows!!

**Comment by GGTY81** [comment]
Work perfectly

**Comment by ruansilvacte** [comment]
Testei mas não funcionou.

**Comment by FlowSistemas** [comment]
Didn't work, test carried out on VPS

**Comment by thiagoorodrigues** [comment]
Funcionando aqui!

**Review by jador-tanner — APPROVED** [review]
Works

**Comment by AlvaroBrasilia** [comment]
Work fine, thank you!

**Review by AlvaroBrasilia — APPROVED** [review]

**Review by ainitech — APPROVED** [review]
Working here!

**Comment by Vitorg96** [comment]
ok

**Review by Vitorg96 — APPROVED** [review]
Work

**Comment by FlowSistemas** [comment]
Funcionando perfeitamente.

**Review by ibinetwork — APPROVED** [review]

**Comment by bobslavtriev** [comment]
LGTM

**Review by bobslavtriev — APPROVED** [review]
LGTM

**Review by ibinetwork — APPROVED** [review]

**Review by salomaolisboa — APPROVED** [review]

**Review by andresayac — APPROVED** [review]
Working

**Comment by w3nder** [comment]
up

**Comment by panalgin** [comment]
@PurpShell can you please review this

**Review by Rippanteq7 — APPROVED** [review]

**Review by Silvioerick — APPROVED** [review]

**Review by devlikepro — APPROVED** [review]

**Review by slntopp — APPROVED** [review]

**Review by panalgin — APPROVED** [review]

**Comment by skyspablo** [comment]
@PurpShell any ETA on releasing the v 6.7.6  to NPM? 🙏🙏🙏

**Review by jgsn13 — COMMENTED** [review]
LGTM!

**Review by Jhonatas56 — COMMENTED** [review]
LGTM!!!!!!

**Comment by AdiKhanOfficial** [comment]
For me that wasn't working then i tried to add 

`to: WABinary_1.S_WHATSAPP_NET,`
instead of 
`to: S_WHATSAPP_NET,`

so now its working fine.

**Pull request merged**
