### PR TITLE
fix: find platform type based on browser second argument

### LINKED ISSUE #481: [BUG] Browser
Browser Logo Not Showing Any Idea To Add Browser Logo

### PR DESCRIPTION
**Pull request by allburov**
fix #481 #228

If we use
```js
browser: ['MyAwesomeApp', 'chrome', '22.5.0']
```
WhatsApp shows the browser's icon in **Linked Devices**
Screenshot_2023-11-05-19-05-01-396_com whatsapp (1)

### CODE REVIEW

**Comment by FERDIZ-afk** [comment]
Can fi be used in the pairing code?

**Review by azudindaem — APPROVED** [review]
LGTM

**Comment by allburov** [comment]
The linter goes crazy about not changed code, idk what to do here. Let me know if I need to adjust the code somehow!

**Review by Ismananda — APPROVED** [review]
I think you can make the code more concise by changing code
`platformType: proto.DeviceProps.PlatformType.DESKTOP,`
to be
`platformType: WAProto_1.proto.DeviceProps.PlatformType[config.browser[1].toUpperCase()] || proto.DeviceProps.PlatformType.DESKTOP,`

and i think you should check the file on Baileys/src/Socket/Socket.ts in the 528 line inside the code
```
{
   tag: 'companion_platform_display',
   attrs: {},
   content: config.browser[0]
}
```
then change `content: config.browser[0]` to be ``` content: `${config.browser[1]} (${config.browser[0]})` ```
you can fix the issue even when using Pairing Code

Maybe this can answer questions from @FERDIZ-afk  and i hope @PurpShell read this

**Comment by Riders004** [comment]
> Great Job!!!! If it is possible, what do you think in adding two more browsers: `Brave and Tor`?

Add. Firefox brave tor

**Review by Riders004 — APPROVED** [review]

**Comment by onurguven** [comment]
Lgtm

**Comment by allburov** [comment]
>Brave and Tor

Is there any values for this browsers in WhatsApp proto? I didn't see it in the list https://github.com/WhiskeySockets/Baileys/blob/e24947e55ad6e3370de867b258bb33bb9e828c56/WAProto/WAProto.proto#L533-L557

I'll change the solution as @Ismananda mentioned so we can define any values that available in proto!

**Comment by Riders004** [comment]
> LGTM

What is LGTM

**Review by PikaBot-Z — APPROVED** [review]

**Review by PikaBot-Z — APPROVED** [review]

**Comment by Riders004** [comment]
Can this Working For Also For QR Code ?

**Comment by Riders004** [comment]
Pair code mode not working with recent change

**Comment by allburov** [comment]
> Pair code mode not working with recent change

Thank you for the information! To be honest, I haven't tested it :D 

I've reverted the changes - we can process them later in the different PR and merge QR mode for now.

**Comment by allburov** [comment]
>What is LGTM

looks good to me

**Comment by Riders004** [comment]
@allburov This One Working On QR Code And Pair Code  You Can [Check Here](https://github.com/allburov/Baileys/blob/adf055ea0c92d42f68997317dfac91e68a3b1250/src/Utils/validate-connection.ts) And You Can Also Test It  And You Can Make Pull Request

 @adiwajshing @PurpShell @SheIITear @whiskeysockets-bot  @FERDIZ-afk you can merge that request if @allburov he make it

**Comment by Ismananda** [comment]
> I'm qr is working but in pair its say incorrect code what I do

Excuse me, I can see your socket configuration in the browser section
`browser: ["device", "browser", "version"]`

**Comment by Riders004** [comment]
> > I'm qr is working but in pair its say incorrect code what I do
> 
> Excuse me, I can see your socket configuration in the browser section `browser: ["device", "browser", "version"]`

IMG_20231122_214555



That's my Browser Configuration and I also added in my Baileys that i added in my pair code script folder

If you want browser version then you can find on google

**Comment by Ismananda** [comment]
> > > I'm qr is working but in pair its say incorrect code what I do
> > 
> > 
> > Excuse me, I can see your socket configuration in the browser section `browser: ["device", "browser", "version"]`
> 
> IMG_20231122_214555
> 
> That's my Browser Configuration and I also added in my Baileys that i added in my pair code script folder
> 
> If you want browser version then you can find on google

I don't know for sure how it can be an error to you (because I actually don't really understand typescript)
But I use configuration like this `browser: ["Mac OS", "Safari", clVer]` and make an experiment by changing the code in node_modules/baileys as I said earlier and it work for me for qrcode and pairing code
So on the linked device you will see like this
IMG

**Comment by Ismananda** [comment]
So maybe it was unsuccessful because of the differences in the implementation of javascript with typescript or maybe other factors. Thank you for trying my advice and apologize for trouble

**Review by Ismananda — APPROVED** [review]

**Comment by jeankassio** [comment]
Tested today
image

**Review by PurpShell — APPROVED** [review]
lgtm

**Review by SheIITear — APPROVED** [review]
Lgtm

**Comment by PurpShell** [comment]
This is not for the pairing code, this is stupid and incorrect. the second argument is the one for the browser type not the first one. Just reverse

**Comment by Salientekill** [comment]
> fix #481 #228
> 
> If we use
> 
> ```js
> browser: ['MyAwesomeApp', 'chrome', '22.5.0']
> ```
> 
> WhatsApp shows the browser's icon in **Linked Devices** Screenshot_2023-11-05-19-05-01-396_com whatsapp (1)

I tried using your example and it didn't work

**Comment by Riders004** [comment]
> > fix #481 #228
> > If we use
> > ```js
> > browser: ['MyAwesomeApp', 'chrome', '22.5.0']
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > WhatsApp shows the browser's icon in **Linked Devices** Screenshot_2023-11-05-19-05-01-396_com whatsapp (1)
> 
> I tried using your example and it didn't work

Upgrade Baileys

**Comment by Riders004** [comment]
> This is not for the pairing code, this is stupid and incorrect. the second argument is the one for the browser type not the first one. Just reverse

I tried it's working for both pairing code and qr code

**Comment by Riders004** [comment]
> > > > I'm qr is working but in pair its say incorrect code what I do
> > > 
> > > 
> > > Excuse me, I can see your socket configuration in the browser section `browser: ["device", "browser", "version"]`
> > 
> > 
> > IMG_20231122_214555
> > That's my Browser Configuration and I also added in my Baileys that i added in my pair code script folder
> > If you want browser version then you can find on google
> 
> I don't know for sure how it can be an error to you (because I actually don't really understand typescript) But I use configuration like this `browser: ["Mac OS", "Safari", clVer]` and make an experiment by changing the code in node_modules/baileys as I said earlier and it work for me for qrcode and pairing code So on the linked device you will see like this IMG

That browser Config I use that for pairing code you can use in qr code

**Comment by Salientekill** [comment]
> > > fix #481 #228
> > > If we use
> > > ```js
> > > browser: ['MyAwesomeApp', 'chrome', '22.5.0']
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > WhatsApp shows the browser's icon in **Linked Devices** Screenshot_2023-11-05-19-05-01-396_com whatsapp (1)
> > 
> > 
> > I tried using your example and it didn't work
> 
> Upgrade Baileys

I already updated, but it still doesn't work: 

browser: ['MyAwesomeApp', 'chrome', '22.5.0']

**Comment by SheIITear** [comment]
Do not fill this pr with unrelated comments. If you need help ask on the offtopic channel on the discord server.

**Comment by Salientekill** [comment]
> Do not fill this pr with unrelated comments. If you need help ask on the offtopic channel on the discord server.

But it's related to this pr, I tried using the same way as the examples and it didn't work

**Comment by SheIITear** [comment]
> > Do not fill this pr with unrelated comments. If you need help ask on the offtopic channel on the discord server.
> 
> 
> 
> But it's related to this pr, I tried using the same way as the examples and it didn't work

Still this is not the place to ask for help. Locking this pr, you can continue the conversation on the server.

**Pull request merged**
