### PR TITLE
Added useSingleFileAuthState and fixed requestPairingCode

### PR DESCRIPTION
**Pull request by fann22**
I’ve added useSingleFileAuthState for easier authentication sharing.
Unlike useMultiFileAuthState, which creates a folder with multiple files, useSingleFileAuthState stores authentication in a single file.
This makes it simpler and more convenient to share or transfer without the hassle of managing multiple files.

### CODE REVIEW

**Comment by fann22** [comment]
fixed precondition required issue with requestPairingCode

code for connection:
```
const P = (await import("pino")).default({ level: "silent" });
const sock = makeWASocket({
    auth: {
        creds: state.creds,
        keys: makeCacheableSignalKeyStore(state.keys, P),
    },
    logger: P,
    browser: Browsers.windows("Chrome"),
    printQRInTerminal: false
}}

if (!sock.authState.creds.registered) {
    let code = await sock.requestPairingCode('62.........64');
    code = code?.match(/.{1,4}/g)?.join("-") || code;
  console.log("Your Pairing Code :", code);
}
k
```

output before the changes:
```
/data/data/com.termux/files/home/wa/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:57
            throw new boom_1.Boom('Connection Closed', { statusCode: Types_1.DisconnectReason.connectionClosed });
                  ^

Error: Connection Closed                                                                                      at sendRawMessage (/data/data/com.termux/files/home/wa/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:57:19)
    at sendNode (/data/data/com.termux/files/home/wa/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:76:16)
    at Object.requestPairingCode (/data/data/com.termux/files/home/wa/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:370:15)                                                                             at async file:///data/data/com.termux/files/home/wa/test.js:92:16 {                                 data: null,
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 428,
    payload: {                                                                                                  statusCode: 428,
      error: 'Precondition Required',
      message: 'Connection Closed'
    },
    headers: {}
  }
}

Node.js v22.8.0
```


output after the changes:
```
Your Pairing Code : 54K2-FT7J
```

**Review by sersawy — APPROVED** [review]

**Comment by SheIITear** [comment]
I don't see any reason to revert back to single file auth, its terrible.

**Comment by SheIITear** [comment]
> > I don't see any reason to revert back to single file auth, its terrible.
> 
> it was there before? i didn't know about that

Yes, it was removed in commit 5aaefa94d6dda04da68e8394ac4b2c858d19ae18.

**Comment by fann22** [comment]
> > > I don't see any reason to revert back to single file auth, its terrible.
> > 
> > 
> > it was there before? i didn't know about that
> 
> Yes, it was removed in commit [5aaefa9](https://github.com/WhiskeySockets/Baileys/commit/5aaefa94d6dda04da68e8394ac4b2c858d19ae18).

do u know why they decided to remove it?

**Comment by SheIITear** [comment]
> > > > I don't see any reason to revert back to single file auth, its terrible.
> > > 
> > > 
> > > it was there before? i didn't know about that
> > 
> > 
> > Yes, it was removed in commit [5aaefa9](https://github.com/WhiskeySockets/Baileys/commit/5aaefa94d6dda04da68e8394ac4b2c858d19ae18).
> 
> do u know why they decided to remove it?

Because it has more faults that uses.

**Comment by Salientekill** [comment]
> I don't see any reason to revert back to single file auth, its terrible.

Not if it's a database

**Comment by SheIITear** [comment]
> > I don't see any reason to revert back to single file auth, its terrible.
> 
> Not if it's a database

What?

**Comment by Salientekill** [comment]
> > > I don't see any reason to revert back to single file auth, its terrible.
> > 
> > 
> > Not if it's a database
> 
> What?

Previously, JSON was used, so a database to store the connection would be better, but from what I saw, this will arrive in 6.8, right?

**Comment by SheIITear** [comment]
> > > > I don't see any reason to revert back to single file auth, its terrible.
> > > 
> > > 
> > > Not if it's a database
> > 
> > 
> > What?
> 
> Previously, JSON was used, so a database to store the connection would be better, but from what I saw, this will arrive in 6.8, right?

How is this related to single file auth though?

**Comment by canove** [comment]
It lacks on performance. Re-writing a single file for every session/key update is unreliable. closing

**Comment by AstroX11** [comment]
I just checked bro's commit he's bloody drunk

**Pull request closed without merging**
