### PR TITLE
ci: Fixed docs build

### PR DESCRIPTION
**Pull request by edgardmessias**

### CODE REVIEW

**Comment by burstfreeze-alt** [comment]
That's what I tried in https://github.com/burstfreeze-alt/Baileys/commit/f6e424d6da1ee261850f0868cf73b245a4c8b5ac and it didn't work for me, but I didn't update package.json which may do the trick.

I will try it again now with your PR and let you know

**Comment by burstfreeze-alt** [comment]
My fork is now the same as your PR and I still see the same issue that I have described in issue #10: https://github.com/burstfreeze-alt/Baileys/actions/runs/4768383437/jobs/8477648224#step:7:1311

Have you tested the workflow in your repo, did it work there?

**Comment by edgardmessias** [comment]
@burstfreeze-alt  yes, the installation worked, I opened another PR to fix the GitHub action (#13)

**Comment by burstfreeze** [comment]
I don't understand how the #13 fixes it however. On the original repo it wasn't required either, what has changed that #13 is required to make the workflow pass?

**Comment by burstfreeze** [comment]
It's the same issue in your workflow as well: https://github.com/edgardmessias/Baileys/actions/runs/4768522599/jobs/8477935307#step:7:1311

**Comment by edgardmessias** [comment]
@burstfreeze @burstfreeze-alt I fixed it change the action to publish

**Comment by burstfreeze-alt** [comment]
I'm still seeing this issue on my repository 😅

https://github.com/burstfreeze-alt/Baileys/actions/runs/4768656028/jobs/8478212725#step:7:706

Can you spot a meaningful difference in my repository and yours?

**Comment by edgardmessias** [comment]
I made a last change, I added this: 

```yml
permissions:
  contents: write
```

**Review by Auties00 — APPROVED** [review]

**Comment by burstfreeze-alt** [comment]
That worked, good job! 🎉🎉🎉

image

I don't understand why the write permission would be required compared to the original repository but it looks reasonable enough to me 😅

I was also able to clone, then yarn and run the example without issues. 

Approval from my end

**Review by burstfreeze — APPROVED** [review]

**Pull request merged**
