### PR TITLE
PDO protocol (peer data operation): Get more history sync + better message retry mechanism

### PR DESCRIPTION
**Pull request by PurpShell**

### CODE REVIEW

**Review by azudindaem — APPROVED** [review]
Tested and implemented

**Comment by adithyan-hermit** [comment]
How to use  sock.fetchMessageHistory

**Comment by w3nder** [comment]
nice

**Comment by azudindaem** [comment]
> How to use sock.fetchMessageHistory

get from the last conversation that you have.. after calling the fetchMessageHistory function, you will receive a message history notification, and here you can retrieve the last 50 messages from the chat..

```js
const messageId = await sock.fetchMessageHistory(
	50,
	{
    	"remoteJid": "xxx@s.whatsapp.net",
		"fromMe": false,
		"id": "0054381C1C7B869DF00AF"
	},
	1700990261
)
```

**Comment by adithyan-hermit** [comment]
> > How to use sock.fetchMessageHistory
> 
> get from the last conversation that you have.. after calling the fetchMessageHistory function, you will receive a message history notification, and here you can retrieve the last 50 messages from the chat..
> 
> ```js
> const messageId = await sock.fetchMessageHistory(
> 	50,
> 	{
>     	"remoteJid": "xxx@s.whatsapp.net",
> 		"fromMe": false,
> 		"id": "0054381C1C7B869DF00AF"
> 	},
> 	1700990261
> )
> ```

 But sock.fetchMessageHistory is not a function in whiskeysockets/baileys@WhiskeySockets/Baileys#feature/pdo-sync it's not defined in sock

**Comment by azudindaem** [comment]
You can use `await sock.sendPeerDataOperationMessage(pdoMessage)` from outside. `pdoMessage` is a straightforward example for your implementation

**Comment by kwangmeng** [comment]
> You can use `await sock.sendPeerDataOperationMessage(pdoMessage)` from outside. `pdoMessage` is a straightforward example for your implementation

Hi @azudindaem, can you help me to understand that means the sendPeerDataOperationMessage(pdoMessage) function will return a WaMessage Object ?

**Comment by kwangmeng** [comment]
> You can use `await sock.sendPeerDataOperationMessage(pdoMessage)` from outside. `pdoMessage` is a straightforward example for your implementation

Implemented and tested

**Comment by sudhansupujari** [comment]
> You can use `await sock.sendPeerDataOperationMessage(pdoMessage)` from outside. `pdoMessage` is a straightforward example for your implementation

please  provide some example , how to use ?

**Comment by PurpShell** [comment]
Will add today, no need for implementations

**Comment by kyraex** [comment]
> Will add today, no need for implementations

Does this will perform better than the current setup? Right now i only handle manual ack whenever a message is missing from node at an interval until the message is arrived. Sometimes it never arrive...

**Review by itsmeJithin — APPROVED** [review]

**Pull request merged**
