### PR TITLE
bump: sharp to ^0.32.2

### PR DESCRIPTION
**Pull request by MuhammedKpln**

### CODE REVIEW

**Review by DavidsonGomes — APPROVED** [review]
nice! 😉

**Review by arnaudh458 — APPROVED** [review]
That fix our issue on electron, no regression

**Review by azudindaem — APPROVED** [review]

**Review by PurpShell — APPROVED** [review]
lgtm! thanks for your first contribution!

**Comment by cifuentesmx** [comment]
merging this anytime soon? this could fix issue #576 Because right now I'm unable to deploy because it won't pull v0.30.5

**Pull request merged**
