### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Sammysaam**

### CODE REVIEW

**Comment by bobslavtriev** [comment]
?????????????????????????????????????????????????????????????????????????????????????????????????????????

**Comment by Salientekill** [comment]
> _ No description provided. _

There is an idiot and there is this person above...

**Comment by andresayac** [comment]
Hahahaha closed this please :v

**Comment by amiruldev20** [comment]
🥱

**Comment by shizothetechie** [comment]
Close this PR @PurpShell 😂

**Comment by Guru322** [comment]
Don't say bad words to my pookie🎀
Pookie is new to github💝

**Comment by PurpShell** [comment]
Idk guys this PR looks really good, I'll push in a few hours. I'd like to spam everyone with a photo of Hisoka

**Pull request closed without merging**
