### PR TITLE
Make "logger" optional

### PR DESCRIPTION
**Pull request by allburov**
Later we anyway define logger from defaults it there's no logger

### CODE REVIEW

**Comment by PurpShell** [comment]
linting

**Comment by allburov** [comment]
Fixed! 
Typescript doesn't offer many techniques for type refinements, so it's better to just declare new variables with the right type.

The rest of errors IDK what it complains about, no changes in those files :(

**Comment by arthursimas1** [comment]
this is already addressed in https://github.com/WhiskeySockets/Baileys/pull/757

**Comment by PurpShell** [comment]
> this is already addressed in #757

Didn't like your implementation. Keeping certain patches in different PRs makes it easy to reverse.

**Comment by arthursimas1** [comment]
> makes it easy to reverse (@PurpShell)
not exactly. buuuut the following needs to be done:
- the PR needs to have objective commits (a very specific change): i've made a commit just for linting
image
- the PR should not squash every commit into a single "merge commit"


anyway, i'll remove the commit relevant to your request

**Comment by allburov** [comment]
@PurpShell now it's green, TY!

**Pull request merged**
